# Generated by Django 5.2.8 on 2026-01-03 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card')], max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_scheme', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(help_text='Phone number of wallet owner (e.g., 233244000000)', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be 12-13 digits (e.g., 233244000000)', regex='^\\d{12,13}$')])),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='wallets_wal_owner_905e11_idx'), models.Index(fields=['account_number', 'owner'], name='wallets_wal_account_85a8bc_idx')],
                'unique_together': {('account_number', 'owner')},
            },
        ),
    ]
