# Generated by Django 5.2.8 on 2026-01-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card')], max_length=10)),
                ('account_number', models.CharField(max_length=6)),
                ('account_scheme', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('at', 'AT')], max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account_number', 'account_scheme')},
            },
        ),
    ]
